### ISSUE TITLE
Anonymize Bot issue

### ISSUE THREAD

**Issue by PerseusTheGreat** [luckydonald/pytgbot#10]
Hi @luckydonald 
It seems the `Anonymize Bot` does not respond.
I will be appreciated if you consider/fix that.
Thanks in advance.

**Comment by luckydonald** [comment]
Thanks for your report.

_I forgot to close this issue after fixing it._

**Comment by PerseusTheGreat** [comment]
Thanks for your consideration.
The bot looks like good, but:
It seems the bot does not work as fast as before...
and
It answers more than one time to any forwarded message!
Is this normal?

**Comment by luckydonald** [comment]
That seems to be an issue with the Telegram API calling it multiple times.

I'm not really sure what to do about it, but I'll try and see what I can do.
