### ISSUE TITLE
InputFileFromBlob broken

### ISSUE THREAD

**Issue by ReneZeidler** [luckydonald/pytgbot#6]
[This change](https://github.com/luckydonald/pytgbot/commit/3ea9cdd10ea66977f5e4be840877b035650f559a#diff-2f3fc72e0605c4edb5056647b3157421R69) broke the InputFileFromBlob constructor. The InputFile constructor is called _after_ self.file_blob is set with the file_blob argument defaulting to None. In the InputFile constructor self.file_blob is then reset to None. InputFileFromDisk has the same issue.

InputFileFromURL has a similar issue: It _does_ pass the file_blob argument to the InputFile constructor, therefore causing the deprecation warning to be printed unnecessarily.

Edit: One more thing, InputFileFromBlob is missing in \_\_all\_\_

**Comment by luckydonald** [comment]
I'll have a look sometime this week.

Somehow I wasn't receiving notifications for this repository, sorry.

**Comment by luckydonald** [comment]
Am in the process of updating for the recent changes anyway, so I'll have a look.
