### ISSUE TITLE
Keyboard import issue

### ISSUE THREAD

**Issue by muhammedfurkan** [luckydonald/pytgbot#9]
`from pytgbot.api_types.sendable.reply_markup import ForceReply, ReplyKeyboardHide, ReplyKeyboardMarkup, KeyboardButton
ImportError: cannot import name 'ReplyKeyboardHide' from 'pytgbot.api_types.sendable.reply_markup'`

**Comment by luckydonald** [comment]
I'll have a look. Am at this very moment working on a new release anyway.

**Comment by luckydonald** [comment]
There is no `ReplyKeyboardHide`. You probably wanted to use `ReplyKeyboardRemove` instead?

**Comment by luckydonald** [comment]
I'll assume that is a problem with your code then.
If that's not the case, give me more details, please.
